jobs:
  - job: ubuntu1604
    pool:
      vmImage: 'Ubuntu-16.04'
    displayName: 'Ubuntu 16.04 x86-64'
    steps:
    - script: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update -y
        sudo apt-get install -y libglfw3-dev python2.7-dev libpng16-dev libopenal-dev libluajit-5.1-dev libserialport-dev libsndfile1-dev
        sudo apt-get install -y gcc-8 g++-8
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
        cd ref
        git clone "https://github.com/chriskohlhoff/asio" --depth 1 --branch asio-1-12-2 -q
      displayName: 'Install dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        wget http://www.magicermine.com/trial/ErmineLightTrial.x86_64/ErmineLightTrial.x86_64/ErmineLightTrial.x86_64
        chmod +x ErmineLightTrial.x86_64
        ./ErmineLightTrial.x86_64 bin/* --output=bin/statbin
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/bin'
        artifactName: binaries
      displayName: 'Publish binaries'

  - job: windows_x64
    pool:
      vmImage: 'vs2017-win2016'
    displayName: 'Windows VS2017 x86-64'
    steps:
    - script: |
        cd ref
        git clone "https://github.com/chriskohlhoff/asio" --depth 1 --branch asio-1-12-2 -q
      displayName: 'Download extra dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -A x64
        cmake --build . --config RelWithDebInfo
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/bin'
        artifactName: binaries
      displayName: 'Publish binaries'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/pdb'
        artifactName: symbols
      displayName: 'Publish symbols'

  - job: windows_x32
    pool:
      vmImage: 'vs2017-win2016'
    displayName: 'Windows VS2017 x86'
    steps:
    - script: |
        cd ref
        git clone "https://github.com/chriskohlhoff/asio" --depth 1 --branch asio-1-12-2 -q
      displayName: 'Download extra dependencies'
    - script: |
        mkdir build
        cd build
        cmake .. -A Win32 -T v141_xp
        cmake --build . --config RelWithDebInfo
      displayName: 'Build'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/bin'
        artifactName: binaries
      displayName: 'Publish binaries'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'build/pdb'
        artifactName: symbols
      displayName: 'Publish symbols'
